"""Add quote status price and created time

Revision ID: 12642207514a
Revises: c5f9eeb4b8d6
Create Date: 2026-08-13 16:41:14.304033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12642207514a'
down_revision = 'c5f9eeb4b8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('total_price')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
