"""Add battery size to quote

Revision ID: c5f9eeb4b8d6
Revises: e0edb1b720f1
Create Date: 2026-08-13 16:10:45.819906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f9eeb4b8d6'
down_revision = 'e0edb1b720f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('battery_size', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('battery_size')

    # ### end Alembic commands ###
